server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
    #   defaultZone: http://localhost:8761/eureka
      defaultZone: http://***REMOVED***:8761/eureka

spring:
  application:
    name: eureka_api_gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - 'https://***REMOVED***'
              - 'http://***REMOVED***:443'
              - 'https://localhost:3000'
              - 'http://localhost:3000'
            allow-credentials: true
            allowedHeaders: '*'
            exposed-headers: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
# 로그인이 필요한 작업 : 마이페이지, 소설작성, 댓글,
      routes:
        - id: profile_image_member
          uri: http://***REMOVED***:8011/
          predicates:
            - Path=/member/myPage/image/**, /member/logout
            - Method=GET,PUT,DELETE

        - id: auth_member
          uri: http://***REMOVED***:8011/
          predicates:
            - Path=/member/myPage, /member/logout
            - Method=GET,POST,PUT,DELETE
          filters:
            - AuthenticationHeaderFilter

        - id: auth_novel
          uri: http://***REMOVED***:8012/
          predicates:
            - Path=/comment/**, /write/**, /novel
            - Method=POST,PUT,DELETE
          filters:
            - AuthenticationHeaderFilter

        - id: auth_novel_mypage
          uri: http://***REMOVED***:8012/
          predicates:
            - Path=/novel/like/**, /novel/my/**
            - Method=GET
          filters:
            - AuthenticationHeaderFilter


        - id: member
          uri: http://***REMOVED***:8011/
          predicates:
            - Path=/member/**, /img/member/**

        - id: novel
          uri: http://***REMOVED***:8012/
          predicates:
            - Path=/novel/**, /img/novel/**

        - id: ai
          uri: http://***REMOVED***:8013/
          predicates:
            - Path=/ai/**
        - id: point
          uri: http://***REMOVED***:8014/
          predicates:
            - Path=/point/**
        - id: order
          uri: http://***REMOVED***:8015/
          predicates:
            - Path=/orders/**
        - id: item
          uri: http://***REMOVED***:8016/
          predicates:
            - Path=/items/**
        - id: orderItem
          uri: http://***REMOVED***:8017/
          predicates:
            - Path=/orderItem/**
        - id: search
          uri: http://***REMOVED***:8018/
          predicates:
            - Path=/search/**
        - id: tempTest
          uri: http://***REMOVED***:8111/
          predicates:
            - Path=/tempTest/**

  redis:
    host: ***REMOVED***
    port: 6379


jwt:
  secret: ***REMOVED***
