server:
  port: 8011

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:8761/eureka
      defaultZone: http://***REMOVED***:8761/eureka

spring:
  application:
    name: service_member
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost/members?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: nextnovel
#    password: ***REMOVED***
    url: jdbc:mysql://***REMOVED***:3306/members?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ***REMOVED***
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#  redis:
#    host: localhost
#    port: 6379
  redis:
    host: ***REMOVED***
    port: 6379
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ***REMOVED***
            client-secret: ***REMOVED***
            redirect-uri: https://***REMOVED***/api/member/oauth2/code/google
            scope:
              - email
              - profile

jwt:
  secret: ***REMOVED***
